### ISSUE TITLE
iMessage

### ISSUE THREAD

**Issue by jk3171** [PruvostMaxime/Hackintosh-Predator-300#1]
Hello, 
I am quite new to hackintoshing. I got one working one time, and I remember that iMessage and similar apps did not work; I believe this has something to do with serialnumbers or something. Did you get iMessage to work for yourself by any chance?

Thanks, 
JK3171

**Comment by PruvostMaxime** [comment]
Well, i'm new too on Hackintoshing.

But for my self,even on my Ryzen Build i didn't got iMessage working with serial (and i don't care because Android user heh)

But for example,iCloud works flawless.

**Comment by jk3171** [comment]
I am kind of struggling right now lol. I can't figure out how to use opencore or what do to right now

**Comment by PruvostMaxime** [comment]
I've made this repo with OpenCore btw 
PM me on discord , i'll help you  Maxoooou#8115
