### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [PruvostMaxime/Hackintosh-Predator-300#2]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ??  Right now it's fn + f12 and fn + key pause.  My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by PruvostMaxime** [comment]
Sup,

I don't know,on my predator the keys are the fn + left/right key.

**Comment by marcinkk** [comment]
But how did you manage to determine that this shortcut works.

**Comment by PruvostMaxime** [comment]
Nothing special
