### ISSUE TITLE
2019 version

### ISSUE THREAD

**Issue by saied89** [PruvostMaxime/Hackintosh-Predator-300#3]
Is an of your guide usable for 2019 version?
Also why soon deprecated?
Also can you please direct me to an up to date guide for this stuff?
Complete hackintosh noob here

**Comment by PruvostMaxime** [comment]
Sup,the guide is still valid,i'm working on a better one with Catalina & other things
And it's usable for the Predator with I7-7700HQ yup

**Comment by eduardovaladares** [comment]
Which version of Opencore works with? tried in version 0.59 but it has errors.

**Comment by PruvostMaxime** [comment]
Sup,
The repo was 5 months ago,so it's was Opencore 0.5.3
You should need to adapt it for the newest versions of Opencore

Since i don't own this laptop anymore,the repo will not be updated.
