### ISSUE TITLE
no verbose in opencore 

### ISSUE THREAD

**Issue by specsnerd007** [PruvostMaxime/Hackintosh-Predator-300#4]
I tried using your config but there's no verbose to debug. The bar below the apple logo stops at 100 percent, I'm guessing its because of my nvidia gpu but I cant be sure if I cant see verbose. Is there any way to trigger verbose?

**Comment by PruvostMaxime** [comment]
You can add with "-v" in boot-args in config.plist

But normally it's working fine if you have the correct version of opencore and Mojave at least, i didn't tried on Catalina.

**Comment by specsnerd007** [comment]
I get that -v would work normally but under boot-args everything is in strings there is no " - " (flag) to assing a argument. Im gonna try just to see if that works.

**Comment by PruvostMaxime** [comment]
yeah, just add -v should work fine
