### ISSUE TITLE
WiFi normally working ?

### ISSUE THREAD

**Issue by Sdev22** [PruvostMaxime/Hackintosh-Predator-300#5]
Do I need  change card WiFi or  not  need  also  I download last mojvo version from gibmicos   and but  cant found open core same you use it  only new one 0.6.1 .. I do change everything with your staff but  nothing working ..

**Comment by PruvostMaxime** [comment]
Sup'
Sorry for the delay.

You need to change the wifi card for a compatible one yup.
Also yeah,since Opencore changes the config file at nearly each update..,my EFI should work in 0.5.3

I will not update this repo,since i don't own this laptop anymore

**Comment by Sdev22** [comment]
Aha, but I have small question the keyboard and trackpad doesn't work

**Comment by Sdev22** [comment]
Everything's great also open faster I like it , i found open core same this and everything working great just that's problem☝️

**Comment by PruvostMaxime** [comment]
Yeah this problem is weird with the touchpad / keyboard,because i used my predator as a daily hackintosh,and everything worked (well,the keyboard had no issues,the touchpad,95% of time it's was fine)

I don't really know why,an other people who tested it also had the issue

**Comment by Sdev22** [comment]
I don't know really my keyboard some time work some time not  but touchpad doesn't work I try another drivers and also don't work

**Comment by PruvostMaxime** [comment]
Yeah it's a mystery,and i'm not good enough to see what's wrong
